version: "3"
services:
  db:
    image: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_polish_ci
    environment:
      - MYSQL_ROOT_PASSWORD=pass123
      - MYSQL_DATABASE=contacts_db
      - TZ=Europe/Warsaw
    ports:
      - 6306:3306
  app:
    image: jboss/wildfly
    command: bash -c "/opt/jboss/wildfly/bin/add-user.sh admin admin --silent
      && /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0"
    volumes:
      - ./target/contacts-app-1.0-SNAPSHOT.war:/opt/jboss/wildfly/standalone/deployments/contacts-app-1.0-SNAPSHOT.war
    ports:
      - 4080:8080
      - 5990:9990
    depends_on:
      - db