version: "3"
services:
  mysql:
    image: mysql
    container_name: contacts_db_server
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_polish_ci
    environment:
      - MYSQL_ROOT_PASSWORD=pass123
      - MYSQL_DATABASE=contacts_db
      - TZ=Europe/Warsaw
    volumes:
      - ./contacts-db:/var/lib/mysql
      - ./src/main/resources/contacts-db-script.sql:/docker-entrypoint-initdb.d/contacts-db-script.sql
    expose:
      - 3306
  wildfly:
    image: jboss/wildfly
    container_name: contacts_app_server
    command: bash -c "/opt/jboss/wildfly/bin/add-user.sh admin admin --silent
      && /opt/jboss/wildfly/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0"
    environment:
      - TZ=Europe/Warsaw
    volumes:
      - ./target/contacts-web-app-1.0-SNAPSHOT.war:/opt/jboss/wildfly/standalone/deployments/contacts-web-app-1.0-SNAPSHOT.war
    ports:
      - 4080:8080
      - 80:8080
    depends_on:
      - mysql